WRKDIR : "/hps/nobackup/flicek/research/user/cander21/strandAsym/nascent_release"
STRAIN : "c3h"
PICARD_LOC : "/hps/nobackup/flicek/research/user/cander21/bin"
cluster: bsub
jobs: 25
####all of the following MUST be in ${WRKDIR}/src/${STRAIN}
SAMPLE_LIST : "c3h_sample_list.txt"
ANNOTATION : "c3h_protein_coding_whole_genes.gff"
CHROM_SZ : "c3h.chromSize.main"
BIOMART_ANNO : "c3h_dnds_biomart.csv"
STAR_INDEX : "c3h.starIndex"
EXONS_ANNO : "c3h.exons.bed"
