WRKDIR : "/hps/nobackup/flicek/research/user/cander21/strandAsym/nascent_release"
STRAIN : "caroli"
PICARD_LOC : "/hps/nobackup/flicek/research/user/cander21/bin"
cluster: bsub
jobs: 25
####all of the following MUST be in ${WRKDIR}/src/${STRAIN}
SAMPLE_LIST : "caroli_sample_list.txt"
ANNOTATION : "caroli_protein_coding_whole_genes.gff"
CHROM_SZ : "caroli.chromSize.main"
BIOMART_ANNO : "caroli_dnds_biomart.csv"
STAR_INDEX : "caroli.starIndex"
EXONS_ANNO : "caroli.exons.bed"
